packages:
  - '.'
  - playground
ignoreWorkspaceRootCheck: true
publicHoistPattern:
  - '@kitschpatrol/repo-config'
  - '@kitschpatrol/typescript-config'
  - 'case-police'
  - '*cspell*'
  - '*eslint*'
  - '*knip*'
  - '*mdat*'
  - '*prettier*'
  - '*remark*'
  - '*stylelint*'
allowBuilds:
  core-js: true
  esbuild: true
  puppeteer: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@kitschpatrol/*'
